from . import (
    test_beneficiary_rules,
    test_client_to_beneficiary_conversion,
    test_client_to_beneficiary_conversion_ui,
    test_client_to_member_conversion,
    test_client_to_member_conversion_ui,
    test_former_member_status,
    test_former_member_ui,
    test_member_definitive_end,
    test_member_reactivation,
    test_member_reentry,
    test_member_reentry_ui,
    test_member_registration_correction,
    test_member_withdrawal,
    test_membership_end,
    test_membership_period,
    test_person_identity_correction,
)
